name: Lint GitHub Actions


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check workflow files
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
