name: Code issues

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: rustup install stable
      - uses: Swatinem/rust-cache@v2
      - run: >
          cargo clippy --all-targets --all-features --workspace --no-deps --tests --
          -D clippy::cargo
          -D warnings
          -A clippy::multiple_crate_versions

